### PR TITLE
etcd-backup-operator/controller: add reportBackupStatus

### PR DESCRIPTION
**Pull request by fanminshi**
reportBackupStatus method updates backup status to backup CR

fixes https://github.com/coreos/etcd-operator/issues/1494

### CODE REVIEW

**Comment by fanminshi** [comment]
Create etcd backup CR.
`$ kubectl create -f backup.yaml`
```yaml
# backup.yaml
apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdBackup"
metadata:
  name: example-etcd-cluster
spec:
  clusterName: example-etcd-cluster
  storageType: S3
  s3:
    s3Bucket: jenkins-etcd-operator
    prefix: prefix
    awsSecret: aws
```

Get CR status:
```
$ kubectl get etcdbackups example-etcd-cluster -o yaml
apiVersion: etcd.database.coreos.com/v1beta2
kind: EtcdBackup
metadata:
  clusterName: ""
  creationTimestamp: 2017-10-11T18:13:07Z
  generation: 0
  name: example-etcd-cluster
  namespace: default
  resourceVersion: "248188"
  selfLink: /apis/etcd.database.coreos.com/v1beta2/namespaces/default/etcdbackups/example-etcd-cluster
  uid: d521a17c-aeaf-11e7-a83b-080027dc7a4d
spec:
  clusterName: example-etcd-cluster
  s3:
    awsSecret: aws
    prefix: prefix
    s3Bucket: jenkins-etcd-operator
  storageType: S3
status:
  Reason: ""
  succeeded: true

**Comment by fanminshi** [comment]
via https://jenkins-etcd-public.prod.coreos.systems/job/etcd-operator-e2eslow-pr/566/console

```
18:11:27 time="2017-10-11T18:11:27Z" level=error msg="fail to setup framework: failed to setup etcd operator: failed to wait pod running, it is still pending: still failing after 12 retries" 
18:11:27 FAIL	github.com/coreos/etcd-operator/test/e2e/e2eslow	61.205s
```

**Comment by fanminshi** [comment]
cc/ @hongchaodeng @hasbro17

**Comment by fanminshi** [comment]
all fixed. PTAL cc/ @hongchaodeng

**Comment by hongchaodeng** [comment]
lgtm

**Pull request merged**
