### PR TITLE
*: run hack/test inside test-pod

### PR DESCRIPTION
**Pull request by hasbro17**
ref: #1640 
The test-pod now runs the `hack/test` script instead of `test/pod/test`.

When the test-pod calls `hack/test` the `KUBECONFIG` is unset so that the test framework uses the in cluster kubeconfig.

The RBAC setup from `e2e_pass` is also removed since that should be done outside the `hack/test` script.

/cc @hongchaodeng

### CODE REVIEW

**Comment by hongchaodeng** [comment]
lgtm

**Comment by hasbro17** [comment]
The log collector now runs inside a container.

**Comment by hongchaodeng** [comment]
lgtm

**Comment by hasbro17** [comment]
CI failure. Most probably a flake since the test passed earlier and the only new change was a name change. 
Jenkins logs:
```
22:42:43 --- FAIL: TestResizeCluster5to3 (130.39s)
22:42:43 	crd_util.go:44: creating etcd cluster: test-etcd-qnzpt
22:42:43 	util.go:52: 2017-11-22 22:40:13.022071689 +0000 UTC m=+26.282971733 waiting size (5), healthy etcd members: names ([])
22:42:43 	util.go:52: 2017-11-22 22:40:22.985686837 +0000 UTC m=+36.246586902 waiting size (5), healthy etcd members: names ([])
22:42:43 	util.go:52: 2017-11-22 22:40:32.986726796 +0000 UTC m=+46.247626810 waiting size (5), healthy etcd members: names ([test-etcd-qnzpt-0000])
22:42:43 	util.go:52: 2017-11-22 22:40:42.987277047 +0000 UTC m=+56.248177098 waiting size (5), healthy etcd members: names ([test-etcd-qnzpt-0000 test-etcd-qnzpt-0001])
22:42:43 	util.go:52: 2017-11-22 22:40:52.995119766 +0000 UTC m=+66.256019797 waiting size (5), healthy etcd members: names ([test-etcd-qnzpt-0000 test-etcd-qnzpt-0001])
22:42:43 	util.go:52: 2017-11-22 22:41:02.984922069 +0000 UTC m=+76.245822103 waiting size (5), healthy etcd members: names ([test-etcd-qnzpt-0000 test-etcd-qnzpt-0001 test-etcd-qnzpt-0002])
22:42:43 	util.go:52: 2017-11-22 22:41:12.984617651 +0000 UTC m=+86.245517680 waiting size (5), healthy etcd members: names ([test-etcd-qnzpt-0000 test-etcd-qnzpt-0001 test-etcd-qnzpt-0002])
22:42:43 	util.go:52: 2017-11-22 22:41:22.985332449 +0000 UTC m=+96.246232479 waiting size (5), healthy etcd members: names ([test-etcd-qnzpt-0000 test-etcd-qnzpt-0001 test-etcd-qnzpt-0002 test-etcd-qnzpt-0003 test-etcd-qnzpt-0004])
22:42:43 	util.go:52: 2017-11-22 22:41:23.115392059 +0000 UTC m=+96.376292047 waiting size (3), healthy etcd members: names ([test-etcd-qnzpt-0000 test-etcd-qnzpt-0001 test-etcd-qnzpt-0002 test-etcd-qnzpt-0003 test-etcd-qnzpt-0004])
22:42:43 	util.go:52: 2017-11-22 22:41:33.115807826 +0000 UTC m=+106.376707834 waiting size (3), healthy etcd members: names ([test-etcd-qnzpt-0000 test-etcd-qnzpt-0001 test-etcd-qnzpt-0002 test-etcd-qnzpt-0003 test-etcd-qnzpt-0004])
22:42:43 	util.go:52: 2017-11-22 22:41:43.115998654 +0000 UTC m=+116.376898711 waiting size (3), healthy etcd members: names ([test-etcd-qnzpt-0000 test-etcd-qnzpt-0001 test-etcd-qnzpt-0002 test-etcd-qnzpt-0003 test-etcd-qnzpt-0004])
22:42:43 	util.go:52: 2017-11-22 22:41:53.118912839 +0000 UTC m=+126.379812893 waiting size (3), healthy etcd members: names ([test-etcd-qnzpt-0000 test-etcd-qnzpt-0001 test-etcd-qnzpt-0002 test-etcd-qnzpt-0003 test-etcd-qnzpt-0004])
22:42:43 	util.go:52: 2017-11-22 22:42:03.116948254 +0000 UTC m=+136.377848318 waiting size (3), healthy etcd members: names ([test-etcd-qnzpt-0000 test-etcd-qnzpt-0001 test-etcd-qnzpt-0002 test-etcd-qnzpt-0003 test-etcd-qnzpt-0004])
22:42:43 	util.go:52: 2017-11-22 22:42:13.116918986 +0000 UTC m=+146.377819066 waiting size (3), healthy etcd members: names ([test-etcd-qnzpt-0000 test-etcd-qnzpt-0001 test-etcd-qnzpt-0002 test-etcd-qnzpt-0003 test-etcd-qnzpt-0004])
22:42:43 	util.go:52: 2017-11-22 22:42:23.117048294 +0000 UTC m=+156.377948329 waiting size (3), healthy etcd members: names ([test-etcd-qnzpt-0000 test-etcd-qnzpt-0002 test-etcd-qnzpt-0003 test-etcd-qnzpt-0004])
22:42:43 	resize_test.go:89: failed to resize to 3 members etcd cluster: still failing after 6 retries
22:42:43 	crd_util.go:76: deleting etcd cluster: test-etcd-qnzpt
22:42:43 FAIL
```

@etcd-bot re-test this please

**Comment by hongchaodeng** [comment]
@hasbro17 
Create an issue for it?

From logs, the etcd pod deleted became "Pending".
```
time="2017-11-22T22:41:31Z" level=info msg="removed member (test-etcd-qnzpt-0001) with ID (8503631028721054218)" cluster-name=test-etcd-qnzpt pkg=cluster
time="2017-11-22T22:41:39Z" level=info msg="skip reconciliation: running ([test-etcd-qnzpt-0000 test-etcd-qnzpt-0002 test-etcd-qnzpt-0003 test-etcd-qnzpt-0004]), pending ([test-etcd-qnzpt-0001])"
```

**Pull request merged**
