### PR TITLE
operator: remove s3 operator flags

### PR DESCRIPTION
**Pull request by fanminshi**

### CODE REVIEW

**Comment by hongchaodeng** [comment]
LGTM
Note that we also need to update upgrade docs and CHANGELOG
@fanminshi Do you want to do it here or in a different PR?

**Comment by fanminshi** [comment]
@hongchaodeng I'll add it to this pr.

**Comment by fanminshi** [comment]
@hongchaodeng updated change log. PTAL

**Comment by hongchaodeng** [comment]
lgtm

**Pull request merged**
