### PR TITLE
e2e: change retry timeout to 10s in testEtcdRestoreOperatorForS3Source

### PR DESCRIPTION
**Pull request by fanminshi**
discussed from https://github.com/coreos-inc/vault-operator/pull/255

### CODE REVIEW

**Comment by hongchaodeng** [comment]
We should fix the waiting restore CR part, not this part: https://github.com/coreos/etcd-operator/blob/0f56ce677ae5ef43051877b70683e583dc5d14ec/test/e2e/e2eslow/backup_restore_test.go#L185-L201

**Comment by fanminshi** [comment]
cc/ @hongchaodeng

**Comment by hongchaodeng** [comment]
LGTM

**Comment by fanminshi** [comment]
merge when green!

**Pull request merged**
