### PR TITLE
*: add license to etcd backup operator files

### PR DESCRIPTION
**Pull request by fanminshi**

### CODE REVIEW

**Comment by fanminshi** [comment]
cc/ @hongchaodeng @hasbro17

**Comment by hasbro17** [comment]
LGTM

**Comment by hasbro17** [comment]
@fanminshi just a reminder that we usually keep the commit title in the format `<pkg>: <commit-msg>`. If the changes are across multiple pkgs then just use `*: <commit-msg>`

**Comment by fanminshi** [comment]
@hasbro17 sounds good.

**Comment by fanminshi** [comment]
@etcd-bot retest this please
reason: check if ci runs kubectl 1.8

**Comment by fanminshi** [comment]
ci failure via https://jenkins-etcd-public.prod.coreos.systems/job/etcd-operator-e2eslow-pr/488/
```
21:08:00 Short-lived access for ['gcr.io', 'us.gcr.io', 'eu.gcr.io', 'asia.gcr.io', 'b.gcr.io', 'bucket.gcr.io', 'l.gcr.io', 'launcher.gcr.io', 'appengine.gcr.io', 'us-mirror.gcr.io', 'eu-mirror.gcr.io', 'asia-mirror.gcr.io', 'mirror.gcr.io'] configured.
21:09:23 time="2017-10-03T21:09:23Z" level=error msg="fail to setup framework: failed to setup etcd operator: failed to wait pod running, it is still pending: still failing after 12 retries" 
```

**Comment by hongchaodeng** [comment]
@etcd-bot retest this please

k8s was having some garbage NS not deleted due to cluster resizing issue. Now cleaned up.

**Comment by hongchaodeng** [comment]
@fanminshi 
Tomorrow let's manually try with this branch to reproduce the problem. It happens twice consecutively.

**Comment by hongchaodeng** [comment]
@fanminshi 
Please rebase and run again.

**Comment by fanminshi** [comment]
@hongchaodeng  CI passes this time.

**Pull request merged**
