### PR TITLE
k8sutil: add checkpoint annotation for selfhosted etcd

### PR DESCRIPTION
**Pull request by xiang90**
/cc @aaronlevy

### CODE REVIEW

**Comment by hongchaodeng** [comment]
Failed test
```
--- FAIL: TestEtcdUpgrade (50.91s)
    upgrade_test.go:46: failed to create 3 members etcd cluster: still failing after 6 retries
FAIL
```

It seems like there is a pod always pending, i.e. never starts running.
```
skip reconciliation: running ([test-etcd-4r27n-0000 test-etcd-4r27n-0001]), pending ([test-etcd-4r27n-0002])
```
Seems more like k8s issue.

**Comment by hongchaodeng** [comment]
@etcd-bot retest this please

**Comment by hongchaodeng** [comment]
defer to @aaronlevy for last check

**Comment by hongchaodeng** [comment]
feel free to merge this

**Comment by aaronlevy** [comment]
One question: what about pods which are created when I do something like expand from 1node to 3? Will it use this same spec or is this self-hosted pod special?

Otherwise, code lgtm

**Comment by xiang90** [comment]
> One question: what about pods which are created when I do something like expand from 1node to 3? Will it use this same spec or is this self-hosted pod special?

self hosted is a cluster, not just one pod or container. so it will apply to all.

**Comment by aaronlevy** [comment]
sgtm

**Pull request merged**
