### PR TITLE
*: update backup policy spec

### PR DESCRIPTION
**Pull request by xiang90**

### CODE REVIEW

**Comment by xiang90** [comment]
@etcd-bot retest this please

**Comment by hongchaodeng** [comment]
@etcd-bot retest this please

**Comment by hongchaodeng** [comment]
@etcd-bot retest this please

**Comment by hongchaodeng** [comment]
Disregard previous test result.
I'm in the middle of cleaning up all garbage images in GCE. That might affect testing.

**Comment by hongchaodeng** [comment]
@etcd-bot retest this please

**Comment by hongchaodeng** [comment]
@etcd-bot retest this please

**Comment by hongchaodeng** [comment]
lgtm

**Comment by hongchaodeng** [comment]
fixes https://github.com/coreos/etcd-operator/issues/703

**Pull request merged**
