### PR TITLE
test/pod: save test-pod logs to file

### PR DESCRIPTION
**Pull request by hasbro17**
[skip ci]
ref: #1640 

Open to any opinions on making the logfile name/location configurable.

### CODE REVIEW

**Comment by hongchaodeng** [comment]
We need to save the "test pod's logs" as well.

**Comment by hasbro17** [comment]
@hongchaodeng can you please clarify. This is saving only the test pod's logs. 
`run-test-pod` runs the test pod and prints out its logs to the screen. Now it saves it to a file as well.

**Comment by hongchaodeng** [comment]
> This is saving only the test pod's logs.

No. It's not. Test pod's log is:
```
kubectl logs test-pod
```

**Comment by hongchaodeng** [comment]
Sorry My mistake.. It's saving the test log now.

**Comment by hongchaodeng** [comment]
OK. LGTM

**Comment by fanminshi** [comment]
lgtm

**Comment by hongchaodeng** [comment]
As a follow-up, can you save operators' logs too?

**Comment by hasbro17** [comment]
@hongchaodeng I can try adding that but I suspect that might introduce concurrency in the bash script in trying to get the logs of multiple pods before they are removed.

**Comment by hongchaodeng** [comment]
Let's add that into umbrella issue :)

**Pull request merged**
