### PR TITLE
update k8s client library to 3.0-beta

### PR DESCRIPTION
**Pull request by xiang90**

### CODE REVIEW

**Comment by xiang90** [comment]
for using taints

**Comment by hongchaodeng** [comment]
In framework.go, this line seemed to fail:
```
cli, err := kubernetes.NewForConfig(config)
```

**Comment by hongchaodeng** [comment]
Let me try with 1.6 cluster config to see if it's incompatibility issue

**Comment by hongchaodeng** [comment]
It works with 1.6 cluster. It's a potential regression.

**Comment by xiang90** [comment]
> It works with 1.6 cluster. It's a potential client-go regression.

no surprise... let's upgrade our cluster?

**Comment by hongchaodeng** [comment]
Yes. We need to test with 1.6 and fix regression first.

cc @hasbro17

**Comment by xiang90** [comment]
> cli, err := kubernetes.NewForConfig(config)

do you have any failure logging?

**Comment by hongchaodeng** [comment]
@xiang90 
I test it with additional logging for pinpointing.

**Comment by hongchaodeng** [comment]
@xiang90 
To move forward this PR, can you add the following line to k8sutil.go:
```
import (
  ...
  _ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
)
```

**Comment by xiang90** [comment]
@hongchaodeng ah... that is magic. it works now. i will clean everything up tomorrow.

**Comment by xiang90** [comment]
@hongchaodeng @hasbro17 all fixed. ptal.

**Comment by hasbro17** [comment]
SGTM. More importantly if all the tests are passing it should be fine. Looks like a lot of stuff is now in apimachinery.

**Comment by xiang90** [comment]
@hasbro17 yea. they move common deps on client and server (api types) to apimachinery, which is a correct thing to do. there are other good changes.

**Comment by xiang90** [comment]
@hongchaodeng merging now. i will work on taint next. i will address your feedback in following prs if any. this pr is mostly mechanical changes anyway.

**Pull request merged**
