### PR TITLE
e2e: use absolute retry attempts to avoid rounding

### PR DESCRIPTION
**Pull request by hongchaodeng**

### CODE REVIEW

**Comment by hongchaodeng** [comment]
Stress testing this.

**Comment by hongchaodeng** [comment]
fix https://github.com/coreos/etcd-operator/issues/1256

**Comment by xiang90** [comment]
why skip ci for this? i saw there were ci failures. i am not sure if this is a fix for #1256 unless we can prove it.

**Comment by hongchaodeng** [comment]
The failure will be fixed by second commit.

Yes. We are stress testing it.

**Comment by hongchaodeng** [comment]
So this PR has evolved to do:
- changing all timeout param to explicit retries to avoid rounding
- making up for long overdue debts in e2e code: unifying all retry interval, unifying wait operator ready method

**Comment by hasbro17** [comment]
SGTM. Are the stress tests for this PR running on jenkins?

**Comment by hongchaodeng** [comment]
@hasbro17 
Right. But I think the problem is probably be solved by https://github.com/coreos/etcd-operator/issues/1276 . This PR is mostly refactoring our e2e code, making up for previous debts.

**Comment by hongchaodeng** [comment]
@etcd-bot retest this please

**Comment by hasbro17** [comment]
LGTM if CI passes

**Pull request merged**
