### PR TITLE
contoller/restore-operator: report restore status

### PR DESCRIPTION
**Pull request by fanminshi**

### CODE REVIEW

**Comment by fanminshi** [comment]
cc/ @hongchaodeng @hasbro17

**Comment by hongchaodeng** [comment]
lgtm if manual test succeeds

**Comment by fanminshi** [comment]
manual test:
```
$ kubectl get EtcdRestore restore-s3-cluster-backup -o yaml
apiVersion: etcd.database.coreos.com/v1beta2
kind: EtcdRestore
metadata:
  clusterName: ""
  creationTimestamp: 2017-10-24T21:57:08Z
  generation: 0
  name: restore-s3-cluster-backup
  namespace: default
  resourceVersion: "72420"
  selfLink: /apis/etcd.database.coreos.com/v1beta2/namespaces/default/etcdrestores/restore-s3-cluster-backup
  uid: 47dba43d-b906-11e7-ab67-080027eadbbe
spec:
  backupSpec:
    clusterName: s3-cluster-backup
    s3:
      awsSecret: aws
      prefix: test-prefix
      s3Bucket: jenkins-etcd-operator
    storageType: S3
  clusterSpec:
    baseImage: ""
    size: 3
    version: 3.1.8
status:
  reason: services "s3-cluster-backup-client" already exists
  succeeded: false
```

it seems like there are some other issue on  create svc `s3-cluster-backup-client`. But it is irrelevant to this pr.

**Comment by hongchaodeng** [comment]
Let's move forward.

> it seems like there are some other issue on create svc s3-cluster-backup-client.

Can you follow up with a fix? Thanks!

**Comment by fanminshi** [comment]
@hongchaodeng yeah, I am investigating.

**Pull request merged**
