### PR TITLE
pkg/backup: better error output in getClientWithMaxRev

### LINKED ISSUE #1808: Reflect error in backup manager onto backup CR
Currently the error from here:
https://github.com/coreos/etcd-operator/blob/9caf18bdff18ab8c790ea54f41074d88c901f5b7/pkg/backup/backup_manager.go#L93-L134

are only logged in operator but not reflected to user via CR.

It's not informational to see:
```
failed to get etcd client with maximum kv store revision
```

It'd better to propagate the error message up.

### PR DESCRIPTION
**Pull request by fanminshi**
fixes #1808

### CODE REVIEW

**Comment by hongchaodeng** [comment]
Can you try with the patch and print an example error?

**Comment by hongchaodeng** [comment]
code LGTM

**Comment by fanminshi** [comment]
yeah, i'll do a manual test

**Comment by fanminshi** [comment]
Manual test:

Setting:
* only etcd-backup-operator deployed

Create cr:

```yaml
apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdBackup"
metadata:
  name: example-cluster-backup
spec:
  etcdEndpoints: ['https://example-etcd-client:2379']
  storageType: S3
  s3:
    path: jenkins-testing-operator/vault.etcd.backup
    awsSecret: aws
```

backup_operator output:

```
 level=error msg="error syncing etcd backup (default/example-cluster-backup): failed to save snapshot (create etcd client failed: failed to get etcd client with maximum kv store revision: failed to create etcd client for endpoint (https://example-etcd-client:2379): grpc: timed out when dialing
)" pkg=controller
```

cr output:

```yaml
$ kubectl get etcdbackups example-cluster-backup -o yaml
apiVersion: etcd.database.coreos.com/v1beta2
kind: EtcdBackup
metadata:
...
spec:
  etcdEndpoints:
  - https://example-etcd-client:2379
  s3:
    awsSecret: aws
    path: jenkins-testing-operator/vault.etcd.backup
  storageType: S3
status:
  Reason: |-
    failed to save snapshot (create etcd client failed: failed to get etcd client with maximum kv store revision: failed to create etcd client for endpoint (https://example-etcd-client:2379): grpc: timed out when dialing
    )
  succeeded: false
```

**Comment by hongchaodeng** [comment]
The error seems too long.
Let's move forward this PR first and optimize it later.

**Pull request merged**
