### PR TITLE
Revert "feat(abs): add operator logic"

### PR DESCRIPTION
**Pull request by hongchaodeng**
Reverts coreos/etcd-operator#1369

See https://github.com/coreos/etcd-operator/pull/1369#issuecomment-326150701

### CODE REVIEW

**Comment by hongchaodeng** [comment]
cc @xiang90 @vdice

**Comment by xiang90** [comment]
sorry about the merging. lgtm.

**Comment by hongchaodeng** [comment]
No worry. Thanks for understanding.

**Comment by vdice** [comment]
lgtm; can re-open PR again to further discuss/amend.

**Pull request merged**
