### PR TITLE
pkg/backup/gcs: initial implementation of Google Cloud Storage API

### PR DESCRIPTION
**Pull request by gyuho**
Tested and confirmed that it works.

For https://github.com/coreos/etcd-operator/issues/1109.

I will try the etcd-operation integration later, and try to finish this pending PR https://github.com/coreos/etcd-operator/pull/1126.

### CODE REVIEW

**Comment by brunomcustodio** [comment]
Are there any short-term plans for merging this?

**Comment by gyuho** [comment]
This got outdated due to recent changes in backup operator.

**Comment by oszi** [comment]
Any plans to resurrect this?

**Comment by crimsonfaith91** [comment]
@gyuho Are you available to resume working on this? Otherwise, I can work on this (via another PR).

**Comment by gyuho** [comment]
@crimsonfaith91 Sure. Please, take it.

**Comment by crimsonfaith91** [comment]
@gyuho Thanks!

**Comment by crimsonfaith91** [comment]
Update: there is already an existing PR (#2003) by cpick@. Feel free to close this PR if needed. :)

**Pull request closed without merging**
