### PR TITLE
*: allow getting a specified backup

### PR DESCRIPTION
**Pull request by xiang90**
fix https://github.com/coreos/etcd-operator/issues/1079

### CODE REVIEW

**Comment by xiang90** [comment]
@hongchaodeng can you give this a try?

**Comment by hongchaodeng** [comment]
Test failed.

**Comment by xiang90** [comment]
@etcd-bot test it please.

**Comment by hongchaodeng** [comment]
@etcd-bot retest this please

**Comment by xiang90** [comment]
test added. we do not have any existing tests for status. we need to add them later on though.

**Comment by hongchaodeng** [comment]
OK. Sounds good.

**Comment by hongchaodeng** [comment]
LGTM

**Comment by hongchaodeng** [comment]
Have QA-verified it too

**Pull request merged**
