### PR TITLE
cluster: refactor backup deletion

### PR DESCRIPTION
**Pull request by xiang90**

### CODE REVIEW

**Comment by xiang90** [comment]
@hongchaodeng After second thought, I feel we should make backup manager non-k8s related initially. We probably need to remove `PodSpecWithStorage(*api.PodSpec) *api.PodSpec` from the interface. 

Later on, we probably should make the backup manager manage different backup backends (pv, s3, etc..). Basically backup manager should not be an interface, but backup backend should be.

**Comment by xiang90** [comment]
Or we will end up with duplicating quite a few k8s related logic in each manager.

**Comment by hongchaodeng** [comment]
> Later on, we probably should make the backup manager manage different backup backends (pv, s3, etc..). Basically backup manager should not be an interface, but backup backend should be.

Sounds good.

**Comment by hongchaodeng** [comment]
lgtm

**Pull request merged**
