### PR TITLE
doc: Fix Install Guide URL

### PR DESCRIPTION
**Pull request by directionless**
[skip ci]

### CODE REVIEW

**Comment by hexfusion** [comment]
@etcd-bot ok to test

**Comment by hexfusion** [comment]
@directionless thank you for the PR can you please update your commit message to `doc: Fix Install Guide URL` and I can get this merged, thanks!

**Comment by directionless** [comment]
You want me to amend that commit, and not adjust it on merge? Okay...

**Comment by hexfusion** [comment]
> You want me to amend that commit, and not adjust it on merge? Okay...

I know it seems silly but it is outlined in our style guide and having these commits ready to go will help things get commited faster and eliminate human error. I appreciate the PR.

https://github.com/coreos/etcd-operator/blob/master/CONTRIBUTING.md#format-of-the-commit-message

**Pull request merged**
