### PR TITLE
Replace glide with dep

### PR DESCRIPTION
**Pull request by antoineco**
#### Context

I'm having tremendous difficulties setting up the project's dependencies in a reliable manner using `glide` due to the presence of nested `vendor/` directories (even occasionally with --strip-vendor for some reason):

```console
$ find vendor -name vendor                                                                                                                                                                                                                                                                                                    
vendor                                                                                                                                                                                                                                                                                                                        
vendor/github.com/aws/aws-sdk-go/awsmigrate/awsmigrate-renamer/vendor                                           
vendor/github.com/aws/aws-sdk-go/vendor                                                                    
vendor/github.com/coreos/etcd/cmd/vendor                                                                  
vendor/k8s.io/api/vendor                                                                                       
vendor/k8s.io/apiextensions-apiserver/vendor                                                                    
vendor/k8s.io/apimachinery/vendor                                                                        
vendor/k8s.io/client-go/vendor  
```

```console
$ go install ./cmd/operator
# github.com/coreos/etcd-operator/pkg/util/k8sutil
pkg/util/k8sutil/crd.go:56:13: cannot use "github.com/coreos/etcd-operator/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta literal (type "github.com/coreos/etcd-operator/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta) as type "github.com/coreos/etcd-operator/vendor/k8s.io/apiextensions-apiserver/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta in field value
pkg/util/k8sutil/crd.go:79:110: cannot use "github.com/coreos/etcd-operator/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions literal (type "github.com/coreos/etcd-operator/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions) as type "github.com/coreos/etcd-operator/vendor/k8s.io/apiextensions-apiserver/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions in argument to clientset.ApiextensionsV1beta1().CustomResourceDefinitions().Get
pkg/util/k8sutil/crd.go:108:46: cannot use cfg (type *"github.com/coreos/etcd-operator/vendor/k8s.io/client-go/rest".Config) as type *"github.com/coreos/etcd-operator/vendor/k8s.io/apiextensions-apiserver/vendor/k8s.io/client-go/rest".Config in argument to clientset.NewForConfigOrDie
```

#### Proposal

`dep` on the other hand is now reliable enough to set up vendored dependencies properly. Besides [Glide's authors themselves](https://github.com/Masterminds/glide#golang-dep) recommend using dep:
> The Go community now has the dep project to manage dependencies. Please consider trying to migrate from Glide to dep.

So I went ahead and converted the `glide` configuration to `dep`.

---

<details>
  <summary><code>dep ensure</code> full log</summary>

```console
Importing configuration from glide. These are only initial constraints, and are further refined during the solve process.
Detected glide configuration files...
Converting from glide.yaml and glide.lock...
  Using * as initial constraint for imported dep k8s.io/client-go
  Trying * (c6f8cf2) as initial lock for imported dep k8s.io/client-go
  Using * as initial constraint for imported dep k8s.io/api
  Trying * (926789a) as initial lock for imported dep k8s.io/api
  Using * as initial constraint for imported dep k8s.io/apimachinery
  Trying * (a28c9b0) as initial lock for imported dep k8s.io/apimachinery
  Using * as initial constraint for imported dep k8s.io/apiextensions-apiserver
  Trying * (2bfb07d) as initial lock for imported dep k8s.io/apiextensions-apiserver
  Using ^3.1.9 as initial constraint for imported dep github.com/coreos/etcd
  Trying v3.1.9 (0f4a535) as initial lock for imported dep github.com/coreos/etcd
  Using ^1.0.0 as initial constraint for imported dep github.com/sirupsen/logrus
  Trying v1.0.0 (202f255) as initial lock for imported dep github.com/sirupsen/logrus
  Using ^0.8.0 as initial constraint for imported dep github.com/pkg/errors
  Trying v0.8.0 (645ef00) as initial lock for imported dep github.com/pkg/errors
  Using ^1.10.9 as initial constraint for imported dep github.com/aws/aws-sdk-go
  Trying v1.10.9 (b709581) as initial lock for imported dep github.com/aws/aws-sdk-go
  Using ^0.2.0 as initial constraint for imported dep github.com/coreos/go-semver
  Trying v0.2.0 (8ab6407) as initial lock for imported dep github.com/coreos/go-semver
  Using ^1.0.0 as initial constraint for imported dep github.com/pborman/uuid
  Trying v1.0 (a97ce2c) as initial lock for imported dep github.com/pborman/uuid
  Using ^0.8.0 as initial constraint for imported dep github.com/prometheus/client_golang
  Trying v0.8.0 (c5b7fcc) as initial lock for imported dep github.com/prometheus/client_golang
  Using ^10.3.0-beta as initial constraint for imported dep github.com/Azure/azure-sdk-for-go
  Trying v10.3.0-beta (57db669) as initial lock for imported dep github.com/Azure/azure-sdk-for-go
  Using ^8.3.1 as initial constraint for imported dep github.com/Azure/go-autorest
  Trying v8.3.1 (5432abe) as initial lock for imported dep github.com/Azure/go-autorest
  Using * as initial constraint for imported dep golang.org/x/net
  Trying * (1c05540) as initial lock for imported dep golang.org/x/net
  Using * as initial constraint for imported dep golang.org/x/time
  Trying master (6dc1736) as initial lock for imported dep golang.org/x/time
  Using * as initial constraint for imported dep cloud.google.com/go
  Trying * (3b1ae45) as initial lock for imported dep cloud.google.com/go
  Using * as initial constraint for imported dep github.com/beorn7/perks
  Trying master (4c0e845) as initial lock for imported dep github.com/beorn7/perks
  Using * as initial constraint for imported dep github.com/coreos/go-systemd
  Trying v14 (48702e0) as initial lock for imported dep github.com/coreos/go-systemd
  Using * as initial constraint for imported dep github.com/coreos/pkg
  Trying * (fa29b1d) as initial lock for imported dep github.com/coreos/pkg
  Using * as initial constraint for imported dep github.com/davecgh/go-spew
  Trying * (782f496) as initial lock for imported dep github.com/davecgh/go-spew
  Using * as initial constraint for imported dep github.com/dgrijalva/jwt-go
  Trying * (01aeca5) as initial lock for imported dep github.com/dgrijalva/jwt-go
  Using * as initial constraint for imported dep github.com/emicklei/go-restful
  Trying * (ff4f55a) as initial lock for imported dep github.com/emicklei/go-restful
  Using * as initial constraint for imported dep github.com/emicklei/go-restful-swagger12
  Trying 1.0.1 (dcef7f5) as initial lock for imported dep github.com/emicklei/go-restful-swagger12
  Using * as initial constraint for imported dep github.com/ghodss/yaml
  Trying * (73d445a) as initial lock for imported dep github.com/ghodss/yaml
  Using * as initial constraint for imported dep github.com/go-ini/ini
  Trying * (c787282) as initial lock for imported dep github.com/go-ini/ini
  Using * as initial constraint for imported dep github.com/go-openapi/jsonpointer
  Trying * (46af16f) as initial lock for imported dep github.com/go-openapi/jsonpointer
  Using * as initial constraint for imported dep github.com/go-openapi/jsonreference
  Trying * (13c6e35) as initial lock for imported dep github.com/go-openapi/jsonreference
  Using * as initial constraint for imported dep github.com/go-openapi/spec
  Trying * (6aced65) as initial lock for imported dep github.com/go-openapi/spec
  Using * as initial constraint for imported dep github.com/go-openapi/swag
  Trying * (1d0bd11) as initial lock for imported dep github.com/go-openapi/swag
  Using * as initial constraint for imported dep github.com/gogo/protobuf
  Trying * (c0656ed) as initial lock for imported dep github.com/gogo/protobuf
  Using * as initial constraint for imported dep github.com/golang/glog
  Trying * (44145f0) as initial lock for imported dep github.com/golang/glog
  Using * as initial constraint for imported dep github.com/golang/groupcache
  Trying * (02826c3) as initial lock for imported dep github.com/golang/groupcache
  Using * as initial constraint for imported dep github.com/golang/protobuf
  Trying * (4bd1920) as initial lock for imported dep github.com/golang/protobuf
  Using * as initial constraint for imported dep github.com/google/btree
  Trying * (7d79101) as initial lock for imported dep github.com/google/btree
  Using * as initial constraint for imported dep github.com/google/gofuzz
  Trying * (44d8105) as initial lock for imported dep github.com/google/gofuzz
  Using * as initial constraint for imported dep github.com/googleapis/gnostic
  Trying * (0c51083) as initial lock for imported dep github.com/googleapis/gnostic
  Using * as initial constraint for imported dep github.com/gregjones/httpcache
  Trying * (787624d) as initial lock for imported dep github.com/gregjones/httpcache
  Using * as initial constraint for imported dep github.com/grpc-ecosystem/go-grpc-prometheus
  Trying v1.1 (6b7015e) as initial lock for imported dep github.com/grpc-ecosystem/go-grpc-prometheus
  Using * as initial constraint for imported dep github.com/grpc-ecosystem/grpc-gateway
  Trying * (84398b9) as initial lock for imported dep github.com/grpc-ecosystem/grpc-gateway
  Using * as initial constraint for imported dep github.com/hashicorp/golang-lru
  Trying * (a0d98a5) as initial lock for imported dep github.com/hashicorp/golang-lru
  Using * as initial constraint for imported dep github.com/howeyc/gopass
  Trying master (bf9dde6) as initial lock for imported dep github.com/howeyc/gopass
  Using * as initial constraint for imported dep github.com/imdario/mergo
  Trying * (6633656) as initial lock for imported dep github.com/imdario/mergo
  Using * as initial constraint for imported dep github.com/jmespath/go-jmespath
  Trying master (bd40a43) as initial lock for imported dep github.com/jmespath/go-jmespath
  Using * as initial constraint for imported dep github.com/json-iterator/go
  Trying 1.0.0 (36b1496) as initial lock for imported dep github.com/json-iterator/go
  Using * as initial constraint for imported dep github.com/juju/ratelimit
  Trying master (5b9ff86) as initial lock for imported dep github.com/juju/ratelimit
  Using * as initial constraint for imported dep github.com/mailru/easyjson
  Trying * (d5b7844) as initial lock for imported dep github.com/mailru/easyjson
  Using * as initial constraint for imported dep github.com/matttproud/golang_protobuf_extensions
  Trying * (fc2b8d3) as initial lock for imported dep github.com/matttproud/golang_protobuf_extensions
  Using * as initial constraint for imported dep github.com/peterbourgon/diskv
  Trying v2.0.1 (5f041e8) as initial lock for imported dep github.com/peterbourgon/diskv
  Using * as initial constraint for imported dep github.com/prometheus/client_model
  Trying master (6f38060) as initial lock for imported dep github.com/prometheus/client_model
  Using * as initial constraint for imported dep github.com/prometheus/common
  Trying * (13ba4dd) as initial lock for imported dep github.com/prometheus/common
  Using * as initial constraint for imported dep github.com/prometheus/procfs
  Trying * (65c1f6f) as initial lock for imported dep github.com/prometheus/procfs
  Using * as initial constraint for imported dep github.com/PuerkitoBio/purell
  Trying v1.0.0 (8a29053) as initial lock for imported dep github.com/PuerkitoBio/purell
  Using * as initial constraint for imported dep github.com/PuerkitoBio/urlesc
  Trying * (5bd2802) as initial lock for imported dep github.com/PuerkitoBio/urlesc
  Using * as initial constraint for imported dep github.com/satori/uuid
  Trying master (5bf94b6) as initial lock for imported dep github.com/satori/uuid
  Using * as initial constraint for imported dep github.com/spf13/pflag
  Trying * (9ff6c69) as initial lock for imported dep github.com/spf13/pflag
  Using * as initial constraint for imported dep golang.org/x/crypto
  Trying * (d172538) as initial lock for imported dep golang.org/x/crypto
  Using * as initial constraint for imported dep golang.org/x/oauth2
  Trying * (a6bd8ce) as initial lock for imported dep golang.org/x/oauth2
  Using * as initial constraint for imported dep golang.org/x/sys
  Trying * (7a4fde3) as initial lock for imported dep golang.org/x/sys
  Using * as initial constraint for imported dep golang.org/x/text
  Trying * (b19bf47) as initial lock for imported dep golang.org/x/text
  Using * as initial constraint for imported dep google.golang.org/appengine
  Trying * (24e4144) as initial lock for imported dep google.golang.org/appengine
  Using * as initial constraint for imported dep google.golang.org/grpc
  Trying v1.0.4 (777daa1) as initial lock for imported dep google.golang.org/grpc
  Using * as initial constraint for imported dep gopkg.in/inf.v0
  Trying v0.9.0 (3887ee9) as initial lock for imported dep gopkg.in/inf.v0
  Using * as initial constraint for imported dep gopkg.in/yaml.v2
  Trying * (53feefa) as initial lock for imported dep gopkg.in/yaml.v2
  Using * as initial constraint for imported dep k8s.io/kube-openapi
  Trying * (80f07ef) as initial lock for imported dep k8s.io/kube-openapi
  Locking in master (53be0d3) for transitive dep github.com/petar/GoLLRB
```
</details>

### CODE REVIEW

**Comment by hongchaodeng** [comment]
It's a good move to migrate from glide to dep. Can you create an issue so that we can better do roadmap planning?

> I'm having tremendous difficulties setting up the project's dependencies in a reliable manner using glide due to the presence of nested vendor/ directories (even occasionally with --strip-vendor for some reason)

Why it doesn't work?

**Comment by antoineco** [comment]
Hard for me to tell if the nested vendor directories came from previous caching or from the glide version installed on the target host, I've been facing this issue today for the first after pulling a fresh copy of the repo.

**Comment by hongchaodeng** [comment]
If it's due to caching, can you do `glide cc`?

**Comment by antoineco** [comment]
After a `glide cc` it seems like I can generate a sane vendor directory :+1: I let you decide whether you want to switch to `dep` nevertheless.

**Comment by hongchaodeng** [comment]
> After a glide cc it seems like I can generate a sane vendor directory 

What caused the cache pollution? 

> I let you decide whether you want to switch to dep nevertheless.

That's orthogonal. In long term, it is good move to migrate to dep.
But for your problem, it's some cache pollution problem and we should figure out why.

**Comment by antoineco** [comment]
My guess is that I have other projects using `k8s.io/apiextensions-apiserver`, could it be that glide is reusing the version in cache blindly?

**Comment by hongchaodeng** [comment]
But each step should have its version pinned, and glide should only get that version, right?

In addition, looking at your top comment again I found that you didn't use strip-vendor flag

**Comment by antoineco** [comment]
@hongchaodeng I can't seem to be able to reproduce the conditions in which I was experiencing that failure (whick is a good thing!), so I'm gonna go ahead and close this. Thanks for helping me troubleshooting.

**Pull request closed without merging**
