### PR TITLE
Add option to force path style s3 uploads.

### PR DESCRIPTION
**Pull request by ainmosni**
This patch adds an option to force path style s3 uploads. This is useful
when a third-party s3 endpoint doesn't support the subdomain style
uploads that's default in s3.

This is a fix for #2035.

### CODE REVIEW

**Comment by ainmosni** [comment]
Because of the year change, the generated code verifier complained which prompted me to regenerate all the generated code. This makes the PR a bit more noisy than I'd like. If wanted, I can split up the PRs.

**Comment by hexfusion** [comment]
@ainmosni yeah we don't need to update the year just go ahead and remove that and we can go from there. Thanks!

**Comment by ainmosni** [comment]
@hexfusion Done, cleaned out the generated code.

**Comment by hexfusion** [comment]
@etcd-bot ok to test

**Comment by hexfusion** [comment]
@ainmosni I am terribly sorry I skimmed through this quick and didn't realize these dates were machine generated output. So alas you will need to return these dates so that CI will pass. Again sorry about this, and thanks again for the PR and your time.

**Comment by ainmosni** [comment]
@hexfusion No problem, I regenerated the code to have the local unit tests pass in the first place. 😁 I've readded them.

**Comment by hexfusion** [comment]
@ainmosni this looks good can you rebase these commits as `pkg/*:Add option to force path style s3 uploads.` and update the [CHANGELOG](https://github.com/coreos/etcd-operator/blob/master/CHANGELOG.md#added) please. Ping me when done and I will get this merged.

**Comment by ainmosni** [comment]
@hexfusion Done and done.

**Comment by hexfusion** [comment]
@ainmosni thank you!

**Comment by ainmosni** [comment]
@hexfusion No, thank you, saves me from keeping a custom fork around to use our s3 setup. :)

**Pull request merged**
