### PR TITLE
*: minor improvements on backup status

### PR DESCRIPTION
**Pull request by xiang90**

### CODE REVIEW

**Comment by xiang90** [comment]
@etcd-bot retest this please

**Comment by xiang90** [comment]
@etcd-bot retest this please

**Comment by hongchaodeng** [comment]
With this it did show better result:
```
    backupServiceStatus:
      backupSize: 0.027
      backups: 1                                                                                                                                                                                                  recentBackup:
        creationTime: 2017-02-26T20:10:23.077478376Z                                                                                                                                                                size: 0.023
        timeTookInSecond: 1
        version: 3.1.0
```

**Comment by xiang90** [comment]
@hongchaodeng Can we get this merged?

**Comment by hongchaodeng** [comment]
lgtm

**Pull request merged**
