### PR TITLE
Updated etc to v3.1.0-rc.1

### PR DESCRIPTION
**Pull request by w0mbat**

### CODE REVIEW

**Comment by hongchaodeng** [comment]
We won't update etcd version until 3.1 stable release.
We also need to update vendoring.

**Comment by w0mbat** [comment]
@hongchaodeng ah ok - just thought that the RC would be more stable than the first alpha

**Comment by hongchaodeng** [comment]
@w0mbat 
We haven't seen any major stability problem in etcd3 so far. That includes heavy testing with large scale deployment.

Of course, we encourage your deployment to upgrade to latest etcd version as much as possible. That's why we built etcd operator to do it.

Meanwhile, you can deploy your own yaml.

**Comment by w0mbat** [comment]
@hongchaodeng ok sure - we already used it down-upstream with the rc version

**Pull request closed without merging**
