### PR TITLE
cmd: add parse() to parse flags in etcd backup operator

### PR DESCRIPTION
**Pull request by fanminshi**
add parse() to parse flags.

### CODE REVIEW

**Comment by fanminshi** [comment]
cc/ @hongchaodeng

**Comment by hongchaodeng** [comment]
LGTM

**Comment by fanminshi** [comment]
manual test:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etcd-backup-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: etcd-backup-operator
    spec:
      containers:
      - name: etcd-backup-operator
        image: gcr.io/coreos-k8s-scale-testing/etcd-operator:fanmin
        imagePullPolicy: Always
        command:
          - etcd-backup-operator 
          - -create-crd=false
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
```

output:
```sh
E1215 23:03:56.018161       1 reflector.go:205] github.com/coreos/etcd-operator/pkg/controller/backup-operator/controller.go:47: Failed to list *v1beta2.EtcdBackup: the server could not find the requested resource (get etcdbackups.etcd.database.coreos.com)
```

**Comment by fanminshi** [comment]
merge when green.

**Pull request merged**
