### PR TITLE
example: rename etcd-cluster to example-etcd-cluster

### PR DESCRIPTION
**Pull request by philips**
EtcdCluster is the type so it is a bit confusing that our example
cluster is named etcd-cluster.

### CODE REVIEW

**Comment by xiang90** [comment]
lgtm

**Comment by hongchaodeng** [comment]
We also need to change all occurrences in README.

**Comment by xiang90** [comment]
@hongchaodeng Can you take over this work and change all the names? Thank you!

**Comment by hongchaodeng** [comment]
Sure.
I would like to close this and cherry-pick the commit.

**Comment by xiang90** [comment]
@hongchaodeng Do it.

**Comment by hongchaodeng** [comment]
Closing.
Move to #448

**Pull request closed without merging**
