### PR TITLE
backup: switch on storage type

### PR DESCRIPTION
**Pull request by xiang90**

### CODE REVIEW

**Comment by hongchaodeng** [comment]
lgtm

**Comment by hongchaodeng** [comment]
FYI, we didn't parse it from flags yet.
We would need to parse it when we actually have another option.

**Comment by xiang90** [comment]
@hongchaodeng 

I saw that todo. Can we add a flag -spec-json? And simply marshal json and pass it in?

**Comment by xiang90** [comment]
@hongchaodeng Also I am not sure how are we going to update backup policy on fly. Or users can only choose backup policy when creating the cluster at first time?

**Comment by xiang90** [comment]
```
	e2e_test.go:213: fail to make a latest backup: backupnow (:19999) failed: Get http://:19999/backupnow: dial tcp :19999: getsockopt: connection refused
```

@hongchaodeng any idea?

**Comment by hongchaodeng** [comment]
@xiang90 
Forgot to check pod running.
Will fix it.

**Comment by hongchaodeng** [comment]
@etcd-bot retest this please

**Pull request merged**
