### PR TITLE
*: move backup-operator/main.go to etcd operator cmd

### PR DESCRIPTION
**Pull request by fanminshi**

### CODE REVIEW

**Comment by hongchaodeng** [comment]
Let's create a folder:
```
version/etcd-backup-operator/
```

**Comment by fanminshi** [comment]
@hongchaodeng created version folder.

**Comment by fanminshi** [comment]
@hongchaodeng done remove version from etcd-backup-operator/**

**Comment by hongchaodeng** [comment]
lgtm

**Pull request merged**
